### ISSUE TITLE
Incomplete delegators list when requested for

### ISSUE THREAD

**Issue by Meshugah** [maticnetwork/subgraphs#27]
Only delegators for validator Id 1 and 10 are returning. I believe when specifically queried for, the other validator's delegators are made available.

**Comment by itzmeanjan** [comment]
Not clear to me why. I've also checked but it doesn't make sense.

**Comment by itzmeanjan** [comment]
But if all you want a list of validatorId(s), you rather try 👇 query 


```graphql
{
  validators {
    validatorId
  }
}
```
